/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

public class App {


    public static void main(String[] args) {
        /* ChristmasLights luces = new ChristmasLights();

        System.out.println("------");
        System.out.println(luces.toggleGrid(0,0,2,2));*/

    }

}
